#Removed npm warns: npm --silent --loglevel=error
#Reduced size: use a lighter version of alpine with node and dotnet included.

FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS base
RUN apk add --update nodejs npm
CMD [ "npm", "--silent", "--loglevel=error" ]
WORKDIR /app
EXPOSE 8080

FROM base AS build
WORKDIR /src
COPY ["ChatService.csproj", "./"]
RUN dotnet restore "./ChatService.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "ChatService.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "ChatService.csproj" -c Release -o /app

FROM base AS finish
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ChatService.dll"]