// <auto-generated />
using System;
using System.Collections.Generic;
using ChatService.Contract;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace СhatService.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20211116190837_main")]
    partial class main
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("СhatService.Contract.Attachment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("height")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("src")
                        .HasColumnType("text");

                    b.Property<string>("thumbnail")
                        .HasColumnType("text");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<int>("width")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("СhatService.Contract.Chat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<List<int>>("messages")
                        .HasColumnType("integer[]");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<List<int>>("users")
                        .HasColumnType("integer[]");

                    b.HasKey("ID");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("СhatService.Contract.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<List<int>>("attachments")
                        .HasColumnType("integer[]");

                    b.Property<int>("author")
                        .HasColumnType("integer");

                    b.Property<string>("content")
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("deletedForAll")
                        .HasColumnType("boolean");

                    b.Property<bool>("edited")
                        .HasColumnType("boolean");

                    b.Property<List<int>>("readBy")
                        .HasColumnType("integer[]");

                    b.Property<List<int>>("repliedFrom")
                        .HasColumnType("integer[]");

                    b.Property<List<int>>("usersDelete")
                        .HasColumnType("integer[]");

                    b.HasKey("ID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("СhatService.Contract.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<List<int>>("Chats")
                        .HasColumnType("integer[]");

                    b.Property<string>("avatar")
                        .HasColumnType("text");

                    b.Property<DateTime>("lastActivity")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int[]>("roles")
                        .HasColumnType("integer[]");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
